/***********************************************************************
 *
 *	file: mty_cl.h
 *
 *	Host side of the OpenCL implementation of mty cl
 *
 *	Written by Mads Buvik Sandvei (https://github.com/madsbuvi/, madsbuvi@stud.ntnu.no)
 *
 */

#include <stdint.h>
#include <string.h>
#include "mtytypes.h"
#include "crypt64.h"

//An array of characters that determine what salt to use.
extern char salt_chars[];

//Will contain a list of what ciphertext bits are found in registers and which must be found via
//LDS/Shared memory.

//Not actually used yet, this is something i'll be using the Nvidia cards when i get around to those
//As those have too limited number of registers in their 2.x cards to just throw them all in there.
extern char B_reg[];
extern int cipher_registers;
//CL source of the above, list of defines.
extern char B_cl[];

//Entry point for GPU searching hosts
void *gpu_main(void *dummyarg /* Takes no argument */);

//Initializes items common across GPUs
int gpu_init(uint32_t seed);

//Add this gpu to the list of gpus
int register_gpu();

//increment number of trips generated by this gpu for global statistics.
void register_trips_generated(int gpu, uint64_t n);

//Let statistics thread know the time at which the search started
void set_start_time();

//Epoch time in milliseconds
uint64_t usec();