/***********************************************************************
 *
 *	file: mty_cl.h
 *
 *	Host side of the OpenCL implementation of mty cl
 *
 *	Written by Mads Buvik Sandvei (https://github.com/madsbuvi/, madsbuvi@stud.ntnu.no)
 *
 */

#include <stdint.h>
#include <string.h>
#include "mtytypes.h"
#include "crypt64.h"

//An array of characters that determine what salt to use.
extern char salt_chars[];

//Entry point for GPU searching hosts
void *gpu_main(void *dummyarg /* Takes no argument */);

//Initializes items common across GPUs
int gpu_init();

//Add this gpu to the list of gpus
int register_gpu();

//increment number of trips generated by this gpu for global statistics.
void register_trips_generated(int gpu, uint64_t n);